# Generated by Django 4.0.3 on 2022-03-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=2, upload_to='articles/'),
            preserve_default=False,
        ),
    ]
