# Generated by Django 4.0.3 on 2022-03-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
    ]
