# Generated by Django 4.0.3 on 2022-04-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newsletterrecipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.CharField(max_length=60),
        ),
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
